# Generated by Django 3.2.2 on 2021-06-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta', models.IntegerField()),
                ('ano', models.DateField()),
                ('nome', models.CharField(max_length=150)),
                ('filiacao', models.CharField(max_length=100)),
            ],
        ),
    ]
